name: Build, Push to ECR and Update Kustomize

on:
  push:
    branches:
      - main
permissions:
  contents: write
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set region ${{ secrets.AWS_REGION }}
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image to ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY"
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c 7)
          docker build -t $IMAGE_URI:$IMAGE_TAG -f frontend/Dockerfile frontend/
          docker push $IMAGE_URI:$IMAGE_TAG
          echo "IMAGE_URI=$IMAGE_URI:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Checkout Kustomize Repo
        uses: actions/checkout@v3
        with:
          repository: Ducaster/ingress-kitchen-kustomize
          token: ${{ secrets.PAT_TOKEN }}
          ref: main

      - name: Update Kustomize File
        run: |
          sed -i "s|image:.*|image: $(echo $IMAGE_URI | awk -F: '{print $1}')|g" kustomize/frontdeploy.yaml
          sed -i "s|newTag:.*|newTag: $(echo $IMAGE_URI | awk -F: '{print $2}')|g" kustomize/frontdeploy.yaml

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "ducaster"
          git config --global user.email "kooa3399@kakao.com"

          git add kustomize/frontdeploy.yaml
          git commit -m "Update Kustomize with new image: $IMAGE_URI" || echo "[No changes] Nothing to commit."
          git push https://x-access-token:${PAT_TOKEN}@github.com/Ducaster/ingress-kitchen-kustomize.git main
