name: CI/CD
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - 'README.md'
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: $
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA2KYAMKNADRNS2TUL
          aws-secret-access-key: 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
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set var
        id: set-var
        run: |
          echo ::set-output name=ECR_REGISTRY::$
          echo ::set-output name=ECR_REPOSITORY::demo
          echo ::set-output name=IMAGE_TAG::$(cat VERSION)
      - name: Docker image Build
        id: build-image
        run: |
          docker build \
            -f Dockerfile \
            -t $/$:$ .
      - name: Docker image Push
        id: push-image
        run: |
          docker push $/$:$
